export const kCanceled = Symbol.for('plt.foundation.canceled')
export const kFailedImport = Symbol.for('plt.foundation.failedImport')
export const kHandledError = Symbol.for('plt.foundation.handledError')
export const kMetadata = Symbol.for('plt.foundation.metadata')
export const kTimeout = Symbol.for('plt.foundation.timeout')
