version: '3.3'
services:
  postgresql:
    ports:
      - '127.0.0.1:5432:5432'
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
  mariadb:
    ports:
      - '127.0.0.1:3307:3306'
    image: 'mariadb:11.6'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=graph
  mysql:
    ports:
      - '127.0.0.1:3306:3306'
    image: 'mysql:5.7'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=graph
  mysql8:
    ports:
      - '127.0.0.1:3308:3306'
    image: 'mysql:8'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=graph
  valkey:
    ports:
      - '6379:6379'
    # Important: do not remove the very specific version here. It is used by the test suite in Windows runner.
    image: 'valkey/valkey:8.0.1-alpine3.20'
