packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
allowBuilds:
  '@datadog/pprof': true
  '@fastify/pre-commit': true
  '@nestjs/core': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
autoInstallPeers: true
childConcurrency: 1
hoist: false
minimumReleaseAge: 1440
nodeLinker: hoisted
packageImportMethod: copy
preferSymlinkedExecutables: true
resolutionMode: highest
strictPeerDependencies: false
