/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PlatformaticViteConfig {
  $schema?: string;
  logger?: {
    level: (
      | ("fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent")
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    transport?:
      | {
          target?: string;
          options?: {
            [k: string]: unknown;
          };
        }
      | {
          targets?: {
            target?: string;
            options?: {
              [k: string]: unknown;
            };
            level?: string;
          }[];
          options?: {
            [k: string]: unknown;
          };
        };
    pipeline?: {
      target?: string;
      options?: {
        [k: string]: unknown;
      };
    };
    formatters?: {
      path: string;
    };
    timestamp?: "epochTime" | "unixTime" | "nullTime" | "isoTime";
    redact?: {
      paths: string[];
      censor?: string;
    };
    base?: {
      [k: string]: unknown;
    } | null;
    messageKey?: string;
    customLevels?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  server?: {
    hostname?: string;
    port?: number | string;
    http2?: boolean;
    https?: {
      allowHTTP1?: boolean;
      key:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
      cert:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
      requestCert?: boolean;
      rejectUnauthorized?: boolean;
    };
  };
  watch?:
    | {
        enabled?: boolean | string;
        /**
         * @minItems 1
         */
        allow?: [string, ...string[]];
        ignore?: string[];
      }
    | boolean
    | string;
  application?: {
    basePath?: string;
    outputDirectory?: string;
    include?: string[];
    commands?: {
      install?: string;
      build?: string;
      development?: string;
      production?: string;
    };
  };
  runtime?: {
    preload?: string | string[];
    basePath?: string;
    services?: {
      [k: string]: unknown;
    }[];
    workers?:
      | number
      | string
      | {
          static?: number;
          dynamic?: boolean;
          minimum?: number;
          maximum?: number;
          total?: number;
          maxMemory?: number;
          cooldown?: number;
          gracePeriod?: number;
          [k: string]: unknown;
        };
    workersRestartDelay?: number | string;
    logger?: {
      level: (
        | ("fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent")
        | {
            [k: string]: unknown;
          }
      ) &
        string;
      transport?:
        | {
            target?: string;
            options?: {
              [k: string]: unknown;
            };
          }
        | {
            targets?: {
              target?: string;
              options?: {
                [k: string]: unknown;
              };
              level?: string;
            }[];
            options?: {
              [k: string]: unknown;
            };
          };
      pipeline?: {
        target?: string;
        options?: {
          [k: string]: unknown;
        };
      };
      formatters?: {
        path: string;
      };
      timestamp?: "epochTime" | "unixTime" | "nullTime" | "isoTime";
      redact?: {
        paths: string[];
        censor?: string;
      };
      base?: {
        [k: string]: unknown;
      } | null;
      messageKey?: string;
      customLevels?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    server?: {
      hostname?: string;
      port?: number | string;
      http2?: boolean;
      https?: {
        allowHTTP1?: boolean;
        key:
          | string
          | {
              path?: string;
            }
          | (
              | string
              | {
                  path?: string;
                }
            )[];
        cert:
          | string
          | {
              path?: string;
            }
          | (
              | string
              | {
                  path?: string;
                }
            )[];
        requestCert?: boolean;
        rejectUnauthorized?: boolean;
      };
    };
    reuseTcpPorts?: boolean;
    startTimeout?: number;
    restartOnError?: boolean | number;
    exitOnUnhandledErrors?: boolean;
    gracefulShutdown?: {
      runtime: number | string;
      application: number | string;
    };
    health?: {
      enabled?: boolean | string;
      interval?: number | string;
      gracePeriod?: number | string;
      maxUnhealthyChecks?: number | string;
      maxELU?: number | string;
      maxHeapUsed?: number | string;
      maxHeapTotal?: number | string;
      maxYoungGeneration?: number | string;
      codeRangeSize?: number | string;
    };
    undici?: {
      agentOptions?: {
        [k: string]: unknown;
      };
      interceptors?:
        | {
            module: string;
            options: {
              [k: string]: unknown;
            };
            [k: string]: unknown;
          }[]
        | {
            Client?: {
              module: string;
              options: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
            Pool?: {
              module: string;
              options: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
            Agent?: {
              module: string;
              options: {
                [k: string]: unknown;
              };
              [k: string]: unknown;
            }[];
            [k: string]: unknown;
          };
      [k: string]: unknown;
    };
    httpCache?:
      | boolean
      | {
          store?: string;
          /**
           * @minItems 1
           */
          methods?: [string, ...string[]];
          cacheTagsHeader?: string;
          maxSize?: number;
          maxEntrySize?: number;
          maxCount?: number;
          [k: string]: unknown;
        };
    watch?: boolean | string;
    managementApi?:
      | boolean
      | string
      | {
          logs?: {
            maxSize?: number;
          };
        };
    metrics?:
      | boolean
      | {
          port?: number | string;
          enabled?: boolean | string;
          hostname?: string;
          endpoint?: string;
          auth?: {
            username: string;
            password: string;
          };
          labels?: {
            [k: string]: string;
          };
          /**
           * The label name to use for the application identifier in metrics (e.g., applicationId, serviceId)
           */
          applicationLabel?: string;
          readiness?:
            | boolean
            | {
                endpoint?: string;
                success?: {
                  statusCode?: number;
                  body?: string;
                };
                fail?: {
                  statusCode?: number;
                  body?: string;
                };
              };
          liveness?:
            | boolean
            | {
                endpoint?: string;
                success?: {
                  statusCode?: number;
                  body?: string;
                };
                fail?: {
                  statusCode?: number;
                  body?: string;
                };
              };
          healthChecksTimeouts?: number | string;
          plugins?: string[];
          timeout?: number | string;
          /**
           * Configuration for exporting metrics to an OTLP endpoint
           */
          otlpExporter?: {
            /**
             * Enable or disable OTLP metrics export
             */
            enabled?: boolean | string;
            /**
             * OTLP endpoint URL (e.g., http://collector:4318/v1/metrics)
             */
            endpoint: string;
            /**
             * Interval in milliseconds between metric pushes
             */
            interval?: number | string;
            /**
             * Additional HTTP headers for authentication
             */
            headers?: {
              [k: string]: string;
            };
            /**
             * Service name for OTLP resource attributes
             */
            serviceName?: string;
            /**
             * Service version for OTLP resource attributes
             */
            serviceVersion?: string;
          };
        };
    telemetry?: {
      enabled?: boolean | string;
      /**
       * The name of the application. Defaults to the folder name if not specified.
       */
      applicationName: string;
      /**
       * The version of the application (optional)
       */
      version?: string;
      /**
       * An array of paths to skip when creating spans. Useful for health checks and other endpoints that do not need to be traced.
       */
      skip?: {
        /**
         * The path to skip. Can be a string or a regex.
         */
        path?: string;
        /**
         * HTTP method to skip
         */
        method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";
        [k: string]: unknown;
      }[];
      exporter?:
        | {
            type?: "console" | "otlp" | "zipkin" | "memory" | "file";
            /**
             * Options for the exporter. These are passed directly to the exporter.
             */
            options?: {
              /**
               * The URL to send the traces to. Not used for console or memory exporters.
               */
              url?: string;
              /**
               * Headers to send to the exporter. Not used for console or memory exporters.
               */
              headers?: {
                [k: string]: unknown;
              };
              /**
               * The path to write the traces to. Only for file exporter.
               */
              path?: string;
              [k: string]: unknown;
            };
            additionalProperties?: never;
            [k: string]: unknown;
          }[]
        | {
            type?: "console" | "otlp" | "zipkin" | "memory" | "file";
            /**
             * Options for the exporter. These are passed directly to the exporter.
             */
            options?: {
              /**
               * The URL to send the traces to. Not used for console or memory exporters.
               */
              url?: string;
              /**
               * Headers to send to the exporter. Not used for console or memory exporters.
               */
              headers?: {
                [k: string]: unknown;
              };
              /**
               * The path to write the traces to. Only for file exporter.
               */
              path?: string;
              [k: string]: unknown;
            };
            additionalProperties?: never;
            [k: string]: unknown;
          };
    };
    verticalScaler?: {
      enabled?: boolean;
      maxTotalWorkers?: number;
      maxTotalMemory?: number;
      minWorkers?: number;
      maxWorkers?: number;
      cooldownSec?: number;
      gracePeriod?: number;
      /**
       * @deprecated
       */
      scaleUpELU?: number;
      /**
       * @deprecated
       */
      scaleDownELU?: number;
      /**
       * @deprecated
       */
      timeWindowSec?: number;
      /**
       * @deprecated
       */
      scaleDownTimeWindowSec?: number;
      /**
       * @deprecated
       */
      scaleIntervalSec?: number;
    };
    inspectorOptions?: {
      host?: string;
      port?: number;
      breakFirstLine?: boolean;
      watchDisabled?: boolean;
      [k: string]: unknown;
    };
    applicationTimeout?: number | string;
    messagingTimeout?: number | string;
    env?: {
      [k: string]: string;
    };
    sourceMaps?: boolean;
    scheduler?: {
      enabled?: boolean | string;
      name: string;
      cron: string;
      callbackUrl: string;
      method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
      headers?: {
        [k: string]: string;
      };
      body?:
        | string
        | {
            [k: string]: unknown;
          };
      maxRetries?: number;
      [k: string]: unknown;
    }[];
    policies?: {
      deny: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^.*$".
         */
        [k: string]: string | [string, ...string[]];
      };
    };
  };
  vite?: {
    configFile?: string | boolean;
    devServer?: {
      strict?: boolean;
    };
    ssr?:
      | {
          enabled?: boolean;
          entrypoint: string;
          clientDirectory?: string;
          serverDirectory?: string;
        }
      | boolean;
    notFoundHandler?:
      | boolean
      | string
      | {
          enabled?: boolean;
          path?: string;
          contentType?: string;
          statusCode?: number;
        };
  };
}
