import { deepStrictEqual, ok } from 'node:assert'
import { readdir, writeFile } from 'node:fs/promises'
import { basename, resolve } from 'node:path'
import { test } from 'node:test'
import { changeWorkingDirectory, createTemporaryDirectory, waitForStart, wattpm } from './helper.js'

/*
  Level 0. A directory with no configuration file of any kind boots on inferred defaults and
  nothing is written to disk. v3 detected the application type and wrote a `watt.json` into the
  user's tree so that there would be a file to load — a file that then had to be recognized as
  autogenerated everywhere else, and that a user could easily commit. Synthesis happens in memory
  now, so the tree is left exactly as it was found.
*/
test('build - when no configuration file exists, should boot on inferred defaults and write nothing', async t => {
  const rootDir = await createTemporaryDirectory(t, 'cli-build')
  await writeFile(resolve(rootDir, 'index.js'), '{}', 'utf-8')

  changeWorkingDirectory(t, rootDir)
  const wattProcess = await wattpm('build', rootDir)

  ok(
    wattProcess.stdout.includes(
      `no configuration file found; booting ${rootDir} as @platformatic/node with inferred defaults`
    )
  )
  ok(wattProcess.stdout.includes('All applications have been built.'))

  deepStrictEqual(await readdir(rootDir), ['index.js'])
})

for (const command of ['start', 'dev']) {
  test(`${command} - when no configuration file exists, should boot on inferred defaults and write nothing`, async t => {
    const rootDir = await createTemporaryDirectory(t, 'cli-start')
    await writeFile(
      resolve(rootDir, 'index.js'),
      `
import { createServer } from 'node:http'

createServer((req, res) => {
  res.writeHead(200, { 'content-type': 'application/json', connection: 'close' }).end('{}')
}).listen(3000)
      `,
      'utf-8'
    )

    changeWorkingDirectory(t, rootDir)
    const startProcess = wattpm(command, rootDir)

    t.after(() => {
      startProcess.kill('SIGINT')
      return startProcess.catch(() => {})
    })

    // The synthesized application is named after the directory, which is also its mesh hostname.
    const { url } = await waitForStart(startProcess, basename(rootDir))
    ok(url)

    deepStrictEqual(await readdir(rootDir), ['index.js'])
  })
}
