/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PlatformaticRemixStackable {
  $schema?: string;
  logger?: {
    level: (
      | ("fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent")
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    transport?:
      | {
          target?: string;
          options?: {
            [k: string]: unknown;
          };
        }
      | {
          targets?: {
            target?: string;
            options?: {
              [k: string]: unknown;
            };
            level?: string;
          }[];
          options?: {
            [k: string]: unknown;
          };
        };
    pipeline?: {
      target?: string;
      options?: {
        [k: string]: unknown;
      };
    };
    formatters?: {
      path: string;
    };
    timestamp?: "epochTime" | "unixTime" | "nullTime" | "isoTime";
    redact?: {
      paths: string[];
      censor?: string;
    };
    [k: string]: unknown;
  };
  server?: {
    hostname?: string;
    port?: number | string;
    http2?: boolean;
    https?: {
      allowHTTP1?: boolean;
      key:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
      cert:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
      requestCert?: boolean;
      rejectUnauthorized?: boolean;
    };
  };
  watch?:
    | {
        enabled?: boolean | string;
        /**
         * @minItems 1
         */
        allow?: [string, ...string[]];
        ignore?: string[];
      }
    | boolean
    | string;
  application?: {
    basePath?: string;
    outputDirectory?: string;
    include?: string[];
    commands?: {
      install?: string;
      build?: string;
      development?: string;
      production?: string;
    };
  };
  runtime?: {
    [k: string]: unknown;
  };
  vite?: {
    configFile?: string | boolean;
    devServer?: {
      strict?: boolean;
    };
    ssr?:
      | {
          enabled?: boolean;
          entrypoint: string;
          clientDirectory?: string;
          serverDirectory?: string;
        }
      | boolean;
  };
  remix?: {
    outputDirectory?: string;
  };
}
