/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PlatformaticRemixStackable {
  $schema?: string;
  server?: {
    hostname?: string;
    port?: number | string;
    http2?: boolean;
    https?: {
      key:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
      cert:
        | string
        | {
            path?: string;
          }
        | (
            | string
            | {
                path?: string;
              }
          )[];
    };
  };
  watch?:
    | {
        enabled?: boolean | string;
        /**
         * @minItems 1
         */
        allow?: [string, ...string[]];
        ignore?: string[];
      }
    | boolean
    | string;
  application?: {
    basePath?: string;
    outputDirectory?: string;
    include?: string[];
    commands?: {
      install?: string;
      build?: string;
      development?: string;
      production?: string;
    };
  };
  vite?: {
    configFile?: string | boolean;
    devServer?: {
      strict?: boolean;
    };
    ssr?:
      | {
          enabled?: boolean;
          entrypoint: string;
          clientDirectory?: string;
          serverDirectory?: string;
        }
      | boolean;
  };
  remix?: {
    outputDirectory?: string;
  };
}
