import {
  applicationToEnvVariable,
  createDirectory,
  detectApplicationType,
  ensureLoggableError,
  findRuntimeConfigurationFile,
  getRoot,
  kMetadata,
  loadConfigurationFile as loadRawConfigurationFile,
  logFatalError,
  parseArgs,
  safeRemove,
  saveConfigurationFile
} from '@platformatic/foundation'
import {
  chooseConfigurationFileName,
  isConfigurationFileName,
  serializeConfiguration
} from '@platformatic/foundation/lib/v4/index.js'
import { appendApplications, findAnyConfigurationFile, importedConfiguration } from '@platformatic/generators'
import { loadConfiguration } from '@platformatic/runtime'
import { bold } from 'colorette'
import { execa } from 'execa'
import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { parseEnv } from 'node:util'
import { extract } from 'tar'
import { version } from '../version.js'
import { installDependencies, listApplicationDirectories } from './dependencies.js'

const originCandidates = ['origin', 'upstream']

function parseGitUrl (url) {
  const fragmentIndex = url.indexOf('#')

  if (fragmentIndex === -1) {
    return { url, branch: null }
  }

  const baseUrl = url.substring(0, fragmentIndex)
  const branch = url.substring(fragmentIndex + 1)

  return { url: baseUrl, branch }
}

async function parseLocalFolder (path) {
  // Read the package.json, if any
  const packageJsonPath = resolve(path, 'package.json')
  let packageJson
  try {
    packageJson = JSON.parse(await readFile(packageJsonPath, 'utf-8'))
  } catch {
    packageJson = {}
  }

  let url

  // Detect if there is a git folder and eventually get the remote
  for (const candidate of originCandidates) {
    try {
      const result = await execa('git', ['remote', 'get-url', candidate], {
        cwd: path,
        env: { GIT_DIR: join(path, '.git') }
      })
      url = result.stdout.trim()
      break
    } catch (e) {
      // No-op
    }
  }

  // Check which capability we should use
  const appType = await detectApplicationType(path, packageJson)

  if (!appType) {
    return
  }

  const { name: capability, label } = appType

  return { id: packageJson.name ?? basename(path), url, packageJson, capability, label }
}

export async function appendEnvVariable (envFile, key, value) {
  let contents = ''

  if (existsSync(envFile)) {
    contents = await readFile(envFile, 'utf-8')

    if (contents.length && !contents.endsWith('\n')) {
      contents += '\n'
    }
  }

  contents += `${key}=${value}\n`

  return writeFile(envFile, contents, 'utf-8')
}

async function fixConfiguration (context, logger, root, configOption, skipDependencies, packageManager) {
  const configurationFile = await findRuntimeConfigurationFile(
    logger,
    root,
    configOption,
    true,
    true,
    false,
    context.executableName
  )

  let applications

  if (!configurationFile) {
    /*
      Level 0: no configuration file anywhere, so the root directory is itself the one application
      and there is nothing to read. This replaces the v3 marker dance, in which the missing-config
      fallback wrote a `?autogenerated=true` watt.json into the tree for the sole purpose of being
      recognized here and then treated as though it were not there. Producer and consumer are both
      gone, and nothing is written.
    */
    const path = resolve(root)
    applications = [{ path, id: basename(path) }]
  } else {
    /*
      The paths only, read from the root without evaluating a single application. This command
      exists to install the capability an application is missing and to write the configuration
      file it does not have, and a full load needs both of those to be there already: an
      autoloaded directory that declares no capability is exactly the case this reports on, and
      the loader refuses it before the report can be made.
    */
    applications = await listApplicationDirectories(configurationFile)
  }

  // For each application, if there is no watt.json, create one and fix package dependencies
  for (const { path } of applications) {
    // Both dialects, because a v4 file that goes unseen here is one this command would overwrite.
    const wattConfiguration = await findAnyConfigurationFile(resolve(root, path))

    const appType = await parseLocalFolder(resolve(root, path))

    /* c8 ignore next 3 - covered */
    if (!appType) {
      return logFatalError(logger, `The path ${bold(path)} does not contain a supported application.`)
    }

    const { id, packageJson, capability, label } = appType

    /*
      A Level 0 root gets no file: it is a single-application project whose configuration is
      exactly what synthesis infers, and writing a defaults-only file there would only pin what is
      already the default. Under a root that does exist, an application still gets its own file --
      owning one is the scope declaration.
    */
    if (!wattConfiguration && configurationFile) {
      await writeApplicationConfiguration(configurationFile, resolve(root, path), capability)
    }

    packageJson.dependencies ??= {}

    if (!packageJson.dependencies[capability]) {
      packageJson.dependencies[capability] = `^${version}`
      delete packageJson.devDependencies?.[capability]

      if (capability === '@platformatic/node') {
        logger.info(
          `Application ${bold(id)} is a ${bold('generic Node.js application')}. Adding ${bold(capability)} to its package.json dependencies.`
        )
      } else {
        logger.info(
          `Application ${bold(id)} is using ${bold(label)}. Adding ${bold(capability)} to its package.json dependencies.`
        )
      }

      await saveConfigurationFile(resolve(path, 'package.json'), packageJson)
    }
  }

  if (!skipDependencies) {
    return await installDependencies(logger, root, applications, false, packageManager)
  }
}

/*
  The configuration file an imported application gets, when it does not already have one. Which
  dialect it is written in follows the root: a `watt.json` beside a v4 root is the coexistence the
  loader refuses, so a project half-converted by this command would not boot.
*/
async function writeApplicationConfiguration (configurationFile, directory, capability) {
  if (isConfigurationFileName(basename(configurationFile))) {
    const name = await chooseConfigurationFileName(directory)

    await writeFile(resolve(directory, name), importedConfiguration(capability), 'utf-8')
    return
  }

  await saveConfigurationFile(resolve(directory, 'watt.json'), {
    $schema: `https://schemas.platformatic.dev/${capability}/${version}.json`
  })
}

/*
  A configless tree has nothing to import into: the application being imported has to be recorded
  somewhere, and Level 0 synthesis describes exactly one application -- the root directory itself --
  so it cannot describe a second. The thin autoload root is the smallest configuration that is
  genuinely load-bearing (the autoload path is a real decision, unlike the defaults synthesis
  already supplies), and it is the same file the wizard writes for a multi-application project.
*/
async function scaffoldAutoloadRoot (logger, root) {
  const name = await chooseConfigurationFileName(root)
  const path = resolve(root, name)

  await createDirectory(resolve(root, 'web'))
  await writeFile(path, `export default ${serializeConfiguration({ autoload: { path: 'web' } })}\n`, 'utf-8')

  logger.info(`Created ${bold(name)} with an ${bold('autoload')} of ${bold('web')}.`)

  return path
}

/*
  Adding an application to a v4 root. The root is a program, so it is edited as source rather than
  round-tripped through its loaded value -- see `appendApplications`. When its shape is not one that
  can be edited, the entry is printed for the user to paste and the command still succeeds: nothing
  was written, and there is nothing to undo.
*/
async function importApplicationIntoV4 (logger, configurationFile, { id, path, url, branch }) {
  const root = dirname(configurationFile)
  const entry = { id }

  /*
    A literal relative path, wherever the application sits. v3 wrote `{PLT_APPLICATION_<ID>_PATH}`
    and an `.env` line for anything outside the root; the indirection bought nothing and cost the
    project a value that reads as the root itself in every clone missing the gitignored file it
    lived in.
  */
  if (path) {
    /*
      Forward slashes whatever the platform. `relative` answers in the local separator, and a
      Windows answer would put `web\main` in a file that gets committed -- unreadable on the next
      machine, and a backslash escape inside the string literal it is written into. Node resolves a
      forward-slash path on Windows, so one spelling works everywhere.
    */
    entry.path = relative(root, resolve(root, path)).split(sep).join('/')
  }

  /*
    A remote application gets no path at all -- v4 backfills an unresolved one from
    `resolvedApplicationsBasePath`, so the absence is the answer rather than an empty string.
  */
  if (url) {
    entry.url = url

    if (branch) {
      entry.gitBranch = branch
    }
  }

  const source = await readFile(configurationFile, 'utf-8')
  const edited = appendApplications(source, [entry])

  if (edited === null) {
    logger.warn(
      `Cannot edit ${bold(basename(configurationFile))} automatically. Add this to its applications:\n\n${serializeConfiguration(entry, 2)}\n`
    )

    return true
  }

  await writeFile(configurationFile, edited, 'utf-8')
  return true
}

async function importApplication (logger, configurationFile, id, path, url, branch) {
  const config = await loadConfiguration(configurationFile)

  /* c8 ignore next 3 - Hard to test */
  if (!config) {
    return
  }

  /*
    A v4 file is edited as source further down, so it is not read as data here -- the parser this
    calls only understands the serialized dialects.
  */
  const rawConfig = isConfigurationFileName(basename(configurationFile))
    ? null
    : await loadRawConfigurationFile(configurationFile)
  const root = dirname(configurationFile)
  const envFile = resolve(root, '.env')
  const envSampleFile = resolve(root, '.env.sample')
  const envVariable = applicationToEnvVariable(id)

  let useEnv = true

  // If there is a locale path
  if (path) {
    let autoloadPath = config.autoload?.path

    // If we already autoload this path, there is nothing to do
    if (autoloadPath) {
      autoloadPath = resolve(root, autoloadPath)
      if (path.startsWith(autoloadPath)) {
        logger.warn('The path is already autoloaded as an application.')
        return
      }
    }

    // If the path is within the application repository
    if (path.startsWith(root)) {
      // If the path is already defined as an application, there is nothing to do
      if (config.applications.some(s => s.path === path)) {
        logger.warn('The path is already defined as an application.')
        return
      }

      // Do not use env variables
      useEnv = false
    }

    if (!url) {
      logger.warn(`The application ${bold(id)} does not define a Git repository.`)
    }
  }

  // Make sure the application is not already defined
  if (config.applications.find(app => app.id === id)) {
    return logFatalError(
      logger,
      `There is already an application ${bold(id)} defined, please choose a different application ID.`
    )
  }

  if (isConfigurationFileName(basename(configurationFile))) {
    return importApplicationIntoV4(logger, configurationFile, { id, path, url, branch })
  }

  /* c8 ignore next */
  rawConfig.web ??= []

  if (useEnv) {
    const resolveConfig = { id, path: `{${envVariable}}`, url }

    if (resolveConfig.url && branch) {
      resolveConfig.gitBranch = branch
    }

    rawConfig.web.push(resolveConfig)

    // Make sure the environment variable is not already defined
    if (existsSync(envFile)) {
      const env = parseEnv(await readFile(envFile, 'utf-8'))

      if (env[envVariable]) {
        return logFatalError(
          logger,
          `There is already an environment variable ${bold(envVariable)} defined, please choose a different application ID.`
        )
      }
    }

    // Copy the .env file to .env.sample if it does not exist
    if (!existsSync(envSampleFile)) {
      await writeFile(envSampleFile, '', 'utf-8')
    }

    await appendEnvVariable(envFile, envVariable, path ?? '')
    await appendEnvVariable(envSampleFile, envVariable, '')
  } else {
    rawConfig.web.push({ id, path: relative(root, path) })
  }

  await saveConfigurationFile(configurationFile, rawConfig)
  return true
}

async function importURL (logger, _, configurationFile, rawUrl, id, http, branch) {
  let url = rawUrl
  if (rawUrl.match(/^[a-z0-9-]+\/[a-z0-9-]+$/i)) {
    url = http ? `https://github.com/${rawUrl}.git` : `git@github.com:${rawUrl}.git`
  }

  const parsed = parseGitUrl(url)
  const effectiveBranch = branch ?? parsed.branch

  await importApplication(
    logger,
    configurationFile,
    id ?? basename(parsed.url, '.git'),
    null,
    parsed.url,
    effectiveBranch
  )
}

async function importLocal (logger, root, configurationFile, path, overridenId) {
  const appType = await parseLocalFolder(resolve(root, path))

  if (!appType) {
    return logFatalError(logger, `The path ${bold(path)} does not contain a supported application.`)
  }

  const { id, url, packageJson, capability } = appType

  if (!(await importApplication(logger, configurationFile, overridenId ?? id, path, url))) {
    return
  }

  // Check if there is any configuration file we recognize. If so, don't do anything
  const wattConfiguration = await findAnyConfigurationFile(resolve(root, path))

  if (wattConfiguration) {
    /* c8 ignore next */
    const displayPath = isAbsolute(path) ? path : relative(root, path)

    logger.info(
      `Path ${bold(resolve(displayPath, wattConfiguration))} already exists. Skipping configuration management ...`
    )
  } else {
    await writeApplicationConfiguration(configurationFile, resolve(root, path), capability)
  }

  packageJson.dependencies ??= {}
  packageJson.dependencies[capability] = `^${version}`

  logger.info(
    `Detected capability ${bold(capability)} for application ${bold(id)}, adding to the application dependencies.`
  )

  await saveConfigurationFile(resolve(path, 'package.json'), packageJson)
}

async function resolveNpmApplication (application, root, childLogger) {
  const absolutePath = application.path
  const relativePath = relative(root, absolutePath)
  const pkg = application.url.replace(/^npm:/, '')

  childLogger.info(`Resolving application ${bold(application.id)} ...`)

  // Download the package using npm pack. We do that in a temporary directory.
  let temporaryDirectory
  const originalWorkingDirectory = process.cwd()
  try {
    childLogger.info(`Downloading npm package ${bold(pkg)} into ${bold(relativePath)} ...`)

    temporaryDirectory = join(tmpdir(), `wattpm-utils-resolve--${process.pid}-${Date.now()}`)
    await createDirectory(temporaryDirectory)
    process.chdir(temporaryDirectory)

    // The last line of the output is the name of the generated tarball
    const { stdout } = await execa('npm', ['pack', pkg])
    const archive = stdout.trim().split('\n').at(-1)

    await createDirectory(absolutePath)
    await extract({ file: resolve(temporaryDirectory, archive), cwd: absolutePath, strip: 1 })
  } finally {
    await safeRemove(temporaryDirectory)
    process.chdir(originalWorkingDirectory)
  }
}

async function resolveGitApplication (application, root, childLogger, username, password) {
  const absolutePath = application.path
  const relativePath = relative(root, absolutePath)

  childLogger.info(`Resolving application ${bold(application.id)} ...`)

  const parsedGitUrl = parseGitUrl(application.url)
  let url = parsedGitUrl.url
  const effectiveBranch = application.gitBranch ?? parsedGitUrl.branch

  if (url.startsWith('http') && username && password) {
    const parsed = new URL(url)
    parsed.username ||= username
    parsed.password ||= password
    url = parsed.toString()
  }

  const cloneArgs = ['clone', url, absolutePath, '--single-branch', '--depth', 1]

  let branchLabel = ''
  if (effectiveBranch && effectiveBranch !== 'main') {
    cloneArgs.push('--branch', effectiveBranch)
    branchLabel = ` (branch ${bold(effectiveBranch)})`
  }

  if (username) {
    childLogger.info(
      `Cloning ${bold(application.url)}${branchLabel} as user ${bold(username)} into ${bold(relativePath)} ...`
    )
  } else {
    childLogger.info(`Cloning ${bold(application.url)}${branchLabel} into ${bold(relativePath)} ...`)
  }

  await execa('git', cloneArgs)
}

// The boot commands `--for all` covers. `exec` is every non-boot evaluation and prepares nothing.
const BOOT_COMMANDS = ['dev', 'start', 'build']

/*
  Candidates are matched by id, and an id that resolves to two different clones is refused: one
  directory cannot hold two checkouts, and choosing silently is how a deploy ships the wrong code.
  An id present under some commands and absent under others needs no such treatment — it is fetched,
  and a clone nobody boots costs disk.
*/
function unionApplications (logger, evaluations, root) {
  const byId = new Map()

  /*
    The second question the candidate set answers: which repository each destination is claimed by.
    Two ids may share a checkout deliberately -- the same repository at the same revision, fetched
    once -- and two repository/revision pairs landing in one directory is a project where the second
    clone overwrites the first, or the first is silently kept and the second application runs code
    from another repository.

    Mapped before any existence filtering, because a destination that already holds one of the two
    clones is exactly the case this refusal is for: filtering first would drop the evidence.
  */
  const byDestination = new Map()

  for (const { command, config } of evaluations) {
    /*
      The candidates, not the application list: `enabled` must not hide an entry from resolve. It is
      the supported way to keep an application out of a boot, and the eval worker drops the disabled
      ones before the list ever leaves it — so an entry `enabled: false` hides is one whose clone
      never arrives, and the boot that turns it on fails on a directory nobody fetched. v3 has no
      such record and its list is the one it always was.
    */
    const entries = config[kMetadata]?.v4?.resolveCandidates ?? config.applications

    for (const application of entries) {
      const destination = application.path
        ? resolve(root, application.path)
        : resolve(root, `${config.resolvedApplicationsBasePath}/${application.id}`)

      if (application.url) {
        const pair = `${application.url}@${application.gitBranch ?? ''}`
        const claimed = byDestination.get(destination)

        /*
          Between distinct applications only. One id evaluated under two commands can disagree with
          itself about which revision to fetch, and that is the check below -- reporting it here
          would name the same application twice and describe a collision it does not have.
        */
        if (claimed && claimed.id !== application.id && claimed.pair !== pair) {
          logFatalError(
            logger,
            `Applications ${bold(claimed.id)} and ${bold(application.id)} both resolve into ${bold(destination)}, ` +
              `from ${bold(claimed.pair)} and ${bold(pair)}. Give one of them its own path.`
          )

          return null
        }

        if (!claimed) {
          byDestination.set(destination, { id: application.id, pair })
        }
      }

      const seen = byId.get(application.id)

      if (!seen) {
        byId.set(application.id, { application, command, destination })
        continue
      }

      for (const [label, before, after] of [
        ['url', seen.application.url, application.url],
        ['gitBranch', seen.application.gitBranch, application.gitBranch],
        ['destination path', seen.destination, destination]
      ]) {
        if ((before ?? null) !== (after ?? null)) {
          logFatalError(
            logger,
            `Application ${bold(application.id)} resolves to two different clones: ${label} is ` +
              `${bold(before ?? 'unset')} under ${bold(seen.command)} and ${bold(after ?? 'unset')} under ${bold(command)}.`
          )

          return null
        }
      }
    }
  }

  return [...byId.values()].map(entry => entry.application)
}

export async function resolveApplications (
  logger,
  root,
  configurationFile,
  username,
  password,
  skipDependencies,
  packageManager,
  target = 'start',
  mode,
  production
) {
  const evaluations = []

  /*
    The context resolve evaluates is the named command's, with that command's own defaults, so what
    it prepares for is a context some boot actually produces rather than a synthetic one. An earlier
    design evaluated all four and unioned them unconditionally; that was wrong because topology is
    not separable from the rest of the root callback. The same function that returns the application
    list also throws on a missing dev certificate or awaits a discovery lookup, and evaluating it
    under a command nobody asked for runs all of that.

    The union survives as `--for all`, for a project that genuinely branches topology on `command`.
    Because the operator asked for those evaluations, a failure in any of them fails the run.
  */
  for (const command of target === 'all' ? BOOT_COMMANDS : [target]) {
    const config = await loadConfiguration(configurationFile, null, { command, mode, production })

    /* c8 ignore next 3 - Hard to test */
    if (!config) {
      return
    }

    evaluations.push({ command, config })
  }

  const config = evaluations[0].config
  const applications = unionApplications(logger, evaluations, root)

  if (!applications) {
    return
  }

  // The applications which might be to be resolved are the one that have a URL and either
  // no path defined (which means no environment variable set) or a non-existing path (which means not resolved yet)
  const resolvableApplications = applications.filter(application => {
    if (!application.url) {
      return false
    }

    if (application.path && existsSync(application.path)) {
      logger.warn(`Skipping application ${bold(application.id)} as the path already exists.`)
      return false
    }

    return true
  })

  // Iterate the applications a first time to verify the environment files configuration and which applications must be resolved
  const toResolve = []
  const fetching = new Map()

  // Simply use application.path here
  for (const application of resolvableApplications) {
    if (!application.path) {
      application.path = resolve(root, `${config.resolvedApplicationsBasePath}/${application.id}`)
    }

    const directory = resolve(root, application.path)

    // If the directory already exists, it's either external or already resolved, nothing to do in both cases
    if (!existsSync(directory)) {
      if (!directory.startsWith(root)) {
        logger.warn(
          `Skipping application ${bold(application.id)} as the non existent directory ${bold(
            application.path
          )} is outside the project directory.`
        )
      } else if (fetching.has(directory)) {
        /*
          A destination two applications share deliberately -- same repository, same revision, which
          the union check above already confirmed. Cloning it twice would have the second clone write
          over the first while the first is still being used.
        */
        logger.info(
          `Application ${bold(application.id)} shares the checkout at ${bold(application.path)} with ${bold(fetching.get(directory))}, which is fetched once.`
        )
      } else {
        // This repository must be resolved
        fetching.set(directory, application.id)
        toResolve.push(application)
      }
    } else {
      logger.warn(
        `Skipping application ${bold(application.id)} as the generated path ${bold(
          join(config.resolvedApplicationsBasePath, application.id)
        )} already exists.`
      )
    }
  }

  // Resolve the applications
  for (const application of toResolve) {
    const childLogger = logger.child({ name: application.id })

    let operation
    try {
      if (application.url.startsWith('npm')) {
        operation = 'download npm package'
        await resolveNpmApplication(application, root, childLogger)
      } else {
        operation = 'clone repository'
        await resolveGitApplication(application, root, childLogger, username, password)
      }
    } catch (error) {
      return logFatalError(
        childLogger,
        { error: ensureLoggableError(error) },
        `Unable to ${operation} of the application ${bold(application.id)}.`
      )
    }
  }

  // Install dependencies
  if (!skipDependencies) {
    return await installDependencies(logger, root, toResolve, false, packageManager)
  }
  /* c8 ignore next - Mistakenly reported as uncovered by C8 */
  return true
}

export async function importCommand (logger, args) {
  const {
    values: { config, id, http, branch, 'skip-dependencies': skipDependencies, 'package-manager': packageManager },
    positionals
  } = parseArgs(
    args,
    {
      config: {
        type: 'string',
        short: 'c'
      },
      id: {
        type: 'string',
        short: 'i'
      },
      http: {
        type: 'boolean',
        short: 'H'
      },
      branch: {
        type: 'string',
        short: 'b'
      },
      'skip-dependencies': {
        type: 'boolean',
        short: 's',
        default: false
      },
      'package-manager': {
        type: 'string',
        short: 'P'
      }
    },
    false
  )

  let root
  let rawUrl

  /*
    No arguments = Fix configuration for existing applications.
    One argument = URL
    Two arguments = root and URL
  */
  if (positionals.length === 0) {
    /*
      getRoot() rather than '': an empty string is not a directory, and the v4 walk that now
      answers "is there a configuration file here" refuses to resolve one against the working
      directory on its behalf -- a project with a root config would have been treated as configless
      and its applications never visited.
    */
    return fixConfiguration(this, logger, getRoot(), config, skipDependencies, packageManager)
  } else if (positionals.length === 1) {
    root = getRoot()
    rawUrl = positionals[0]
  } else {
    root = getRoot(positionals)
    rawUrl = positionals[1]
  }

  let configurationFile = await findRuntimeConfigurationFile(
    logger,
    root,
    config,
    true,
    true,
    true,
    this.executableName
  )

  configurationFile ??= await scaffoldAutoloadRoot(logger, root)

  // If the rawUrl exists as local folder, import a local folder, otherwise go for Git.
  // Try a relative from the root folder or from process.cwd().
  const local = [resolve(root, rawUrl), resolve(process.cwd(), rawUrl)].find(c => {
    return existsSync(c)
  })

  if (local) {
    return importLocal(logger, root, configurationFile, local, id)
  }

  return importURL(logger, root, configurationFile, rawUrl, id, http, branch)
}

export async function resolveCommand (logger, args) {
  const {
    values: {
      config,
      username,
      password,
      'skip-dependencies': skipDependencies,
      'package-manager': packageManager,
      for: target,
      mode,
      production
    },
    positionals
  } = parseArgs(
    args,
    {
      config: {
        type: 'string',
        short: 'c'
      },
      /*
        resolve does not default production and mode the way other exec-context commands do: the
        target chosen by --for supplies them, so `--for start` evaluates what `wattpm start` boots.
        The flags override where a deployment is neither — `--for start --mode staging` resolves
        what `wattpm start --mode staging` will boot.
      */
      for: {
        type: 'string',
        default: 'start'
      },
      mode: {
        type: 'string'
      },
      production: {
        type: 'boolean'
      },
      username: {
        type: 'string',
        short: 'u',
        default: process.env.WATTPM_RESOLVE_USERNAME
      },
      password: {
        type: 'string',
        short: 'p',
        default: process.env.WATTPM_RESOLVE_PASSWORD
      },
      'skip-dependencies': {
        type: 'boolean',
        short: 's',
        default: false
      },
      'package-manager': {
        type: 'string',
        short: 'P'
      }
    },
    false
  )

  const root = getRoot(positionals)
  const configurationFile = await findRuntimeConfigurationFile(
    logger,
    root,
    config,
    true,
    true,
    true,
    this.executableName
  )

  if (target !== 'all' && !BOOT_COMMANDS.includes(target)) {
    return logFatalError(
      logger,
      `Invalid value ${bold(target)} for --for. Use one of ${BOOT_COMMANDS.map(c => bold(c)).join(', ')} or ${bold('all')}.`
    )
  }

  const resolved = await resolveApplications(
    logger,
    root,
    // Level 0: the loader is handed the directory and synthesizes. Nothing in a configless tree is
    // a remote application, so this resolves the dependencies and finds nothing to fetch.
    configurationFile ?? root,
    username,
    password,
    skipDependencies,
    packageManager,
    target,
    mode,
    production
  )

  if (resolved) {
    logger.done('All applications have been resolved.')
  }
}

export const help = {
  import: {
    usage: 'import [root] [url]',
    description: 'Imports an external resource as an application',
    args: [
      {
        name: 'root',
        description: 'The directory containing the project (the default is the current directory)'
      },
      {
        name: 'url',
        description: 'The URL to import (can be in the form $USER/$REPOSITORY for GitHub repositories)'
      }
    ],
    options: [
      {
        usage: '-c, --config <config>',
        description: 'Name of the configuration file to use (the default to autodetect it)'
      },
      {
        usage: '-i, --id <value>',
        description: 'The id of the application (the default is the basename of the URL)'
      },
      {
        usage: '-H, --http',
        description: 'Use HTTP URL when expanding GitHub repositories'
      },
      {
        usage: '-b, --branch <branch>',
        description: 'The branch to clone (the default is main)'
      },
      {
        usage: '-s, --skip-dependencies',
        description: 'Do not install applications dependencies'
      },
      {
        usage: '-P, --package-manager <executable>',
        description: 'Use an alternative package manager (the default is to autodetect it)'
      }
    ]
  },
  resolve: {
    usage: 'resolve [root]',
    description: 'Resolves all external applications',
    args: [
      {
        name: 'root',
        description: 'The directory containing the project (the default is the current directory)'
      }
    ],
    options: [
      {
        usage: '-c, --config <config>',
        description: 'Name of the configuration file to use (the default to autodetect it)'
      },
      {
        usage: '-u, --username <value>',
        description: 'The username to use for HTTP URLs'
      },
      {
        usage: '-p, --password <value>',
        description: 'The password to use for HTTP URLs'
      },
      {
        usage: '-s, --skip-dependencies',
        description: 'Do not install applications dependencies'
      },
      {
        usage: '-P, --package-manager <executable>',
        description: 'Use an alternative package manager (the default is to autodetect it)'
      },
      {
        usage: '--for <command>',
        description:
          'Prepare for the given boot command — dev, start or build — or "all" to cover every one (the default is start)'
      },
      {
        usage: '--mode <name>',
        description: 'Override the mode the target command would use'
      },
      {
        usage: '--production',
        description: 'Override the production flag the target command would use'
      }
    ],
    footer () {
      return `
${this.executableId} resolve command resolves runtime applications that have the \`url\` in their configuration.
To change the directory where an application is cloned, you can set the \`path\` property in the application configuration.

After cloning the application, the resolve command will set the relative path to the application in the Platformatic configuration file.

Example of the runtime \`watt.json\` configuration file:

\`\`\`json
{
  "$schema": "https://schemas.platformatic.dev/@platformatic/wattpm/2.0.0.json",
  "applications": [
    {
      "id": "application-1",
      "path": "./applications/application-1",
      "config": "platformatic.json"
    },
    {
      "id": "application-2",
      "config": "platformatic.json",
      "url": "https://github.com/test-owner/test-application.git"
    },
    {
      "id": "application-3",
      "config": "platformatic.json",
      "path": "./custom-external/application-3",
      "url": "https://github.com/test-owner/test-application.git"
    }
  ],
}
\`\`\`

If not specified, the configuration will be loaded from any of the following, in the current directory.

* \`watt.json\`, or
* \`platformatic.application.json\`, or
* \`platformatic.json\`, or
* \`watt.yaml\`, or
* \`platformatic.application.yaml\`, or
* \`platformatic.yaml\`, or
* \`watt.yml\`, or
* \`platformatic.application.yml\`, or
* \`platformatic.yml\`, or
* \`watt.toml\`, or
* \`platformatic.application.toml\`, or
* \`platformatic.toml\`, or
* \`watt.tml\`, or
* \`platformatic.application.tml\`, or
* \`platformatic.tml\`

You can find more details about the configuration format here:
* [Platformatic DB Configuration](https://docs.platformatic.dev/docs/reference/db/configuration)
* [Platformatic Application Configuration](https://docs.platformatic.dev/docs/reference/service/configuration)
    `
    }
  }
}
