import { createEnvFileTool, defaultPackageManager, generateDashedName, safeRemove } from '@platformatic/foundation'
import { LegacyConfigurationFileError, serializeConfiguration } from '@platformatic/foundation/lib/v4/index.js'
import {
  BaseGenerator,
  appendApplications,
  envObjectToString,
  findAnyConfigurationFile,
  listedApplications,
  rawSource,
  readEnvFile,
  getApplicationTemplateFromSchemaUrl
} from '@platformatic/generators'
import { existsSync } from 'node:fs'
import { readFile, readdir, stat } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { basename, join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { getArrayDifference } from './utils.js'

const engines = {
  node: '>=22.19.0'
}

function getRuntimeWrappableProperties () {
  return {
    logger: {
      level: '{PLT_SERVER_LOGGER_LEVEL}'
    },
    managementApi: '{PLT_MANAGEMENT_API}'
  }
}

function getRuntimeBaseEnvVars (config) {
  return {
    PLT_SERVER_LOGGER_LEVEL: config.logLevel || 'info',
    PLT_MANAGEMENT_API: true
  }
}

/*
  The one thing an import changes about a root: which applications it lists. Applied to the module
  the user has rather than to a re-rendering of it, so their formatting, their comments and the
  expressions their values are written as all survive the edit.
*/
export class RuntimeGenerator extends BaseGenerator {
  constructor (opts) {
    super({
      ...opts,
      module: '@platformatic/runtime'
    })
    this.runtimeName = opts.name
    this.applicationsFolder = opts.applicationsFolder ?? 'applications'
    this.applications = []
    this.existingApplications = []
    this.packageManager = opts.packageManager ?? defaultPackageManager
  }

  async addApplication (application, name) {
    // ensure application config is correct
    const originalConfig = application.config
    const applicationName = name || generateDashedName()
    const newConfig = {
      ...originalConfig,
      isRuntimeContext: true,
      applicationName
    }
    // reset all files previously generated by the application
    application.reset()
    application.setConfig(newConfig)
    this.applications.push({
      name: applicationName,
      application
    })

    application.setRuntime(this)
  }

  async generatePackageJson () {
    const template = {
      name: `${this.runtimeName}`,
      scripts: {
        dev: this.config.devCommand ?? 'wattpm dev',
        build: this.config.buildCommand ?? 'wattpm build',
        start: this.config.startCommand ?? 'wattpm start'
      },
      dependencies: {
        wattpm: `^${this.platformaticVersion}`,
        ...this.config.dependencies
      },
      engines
    }

    if (this.packageManager === 'npm' || this.packageManager === 'yarn') {
      template.workspaces = [this.applicationsFolder + '/*']
    }

    if (this.packageManager === 'yarn') {
      template.private = true
    }

    return template
  }

  async _beforePrepare () {
    this.setApplicationsDirectory()
    this.setApplicationsConfigValues()
    this.addApplicationsDependencies()

    this.addEnvVars(getRuntimeBaseEnvVars(this.config), { overwrite: false, default: true })
  }

  addApplicationsDependencies () {
    this.applications.forEach(({ application }) => {
      if (application.config.dependencies) {
        Object.entries(application.config.dependencies).forEach(kv => {
          this.config.dependencies[kv[0]] = kv[1]
        })
      }
    })
  }

  async populateFromExistingConfig () {
    if (this._hasCheckedForExistingConfig) {
      return
    }
    this._hasCheckedForExistingConfig = true
    /*
      Whichever dialect the project is in: a v4 configuration is a module and is invisible to the
      legacy lookup, so without this the wizard treats a project it scaffolded itself as a new one.
    */
    const existingConfigFile = await findAnyConfigurationFile(this.targetDirectory)

    if (existingConfigFile && existsSync(join(this.targetDirectory, existingConfigFile))) {
      const existingConfigPath = join(this.targetDirectory, existingConfigFile)

      this.existingConfigRaw = await this.readConfigurationFile(existingConfigPath, 'root', this.targetDirectory)
      /*
        The file as written, kept so that editing it can be an edit. Re-emitting from the evaluated
        configuration would bake this machine's environment into the user's root -- a reference to
        PLT_SERVER_LOGGER_LEVEL becomes whatever it happens to resolve to here -- and take every
        comment with it.
      */
      this.existingConfigFile = existingConfigFile
      this.existingConfigSource = await readFile(existingConfigPath, 'utf-8')

      /*
        A legacy root is refused with the hint every other v4 entry point gives, rather than loaded
        and rewritten: continuing wrote the v4 module form over the .json file, and migrate is the
        tool whose whole job is that conversion -- with the refusals and divergence reports the
        wizard has no way to make.
      */
      if (existingConfigFile.endsWith('.json')) {
        throw new LegacyConfigurationFileError(existingConfigPath)
      } else {
        /*
          Derived from the root rather than loaded through it. A full load evaluates every
          application's configuration, and those import their capabilities -- so the wizard would
          need the project's dependencies installed before it could read the project, which is
          exactly the state it is called in to fix.
        */
        const { PLT_ROOT, ...existingEnvironment } = await readEnvFile(this.targetDirectory)

        this.config.env = existingEnvironment
        this.existingConfig = this.existingConfigRaw
        this.existingApplications = await this.#listExistingApplications(this.existingConfigRaw)
      }

      this.updateRuntimeConfig(this.existingConfigRaw)
      this.updateRuntimeEnv(await readFile(join(this.targetDirectory, '.env'), 'utf-8'))
    }
  }

  async prepare () {
    await this.populateFromExistingConfig()
    if (this.existingConfig) {
      this.setApplicationsDirectory()
      this.setApplicationsConfigValues()
      await this._afterPrepare()
      return {
        env: this.config.env,
        targetDirectory: this.targetDirectory
      }
    } else {
      return await super.prepare()
    }
  }

  setApplicationsConfigValues () {
    let newApplicationOrdinal = 0
    this.applications.forEach(({ name, application }) => {
      if (!application.config) {
        // set default config
        application.setConfig()
      }
      const existingOrdinal = this.existingApplications.indexOf(name)
      const ordinal = existingOrdinal === -1 ? this.existingApplications.length + newApplicationOrdinal++ : existingOrdinal
      this.setApplicationPort(application, ordinal)
    })
  }

  setApplicationPort (application, ordinal) {
    if (application.config.port === 3042) {
      application.setConfig({ port: 3042 + ordinal })
    }
  }

  /*
    The root is the one v4 configuration that is not a capability factory call: it imports
    `defineConfig` from wattpm, whose whole job is to type its argument.
  */
  /*
    The stamped plain-object form rather than an imported `defineConfig`, which is the machine-writer
    case the `$schema` marker exists for: the wizard writes this file before anything is installed
    and reads it back on a later run, so a root that imported `wattpm` could not be read in the
    state that produced it. A person editing the file afterwards can switch to the imported form.
  */
  serializeConfigFile (config) {
    /*
      Unstamped while this line is still 3.x. The marker is a version declaration, and the loader
      refuses a v3 one outright -- correctly, since that is how it catches a configuration nobody
      migrated. It becomes writable, and worth writing, at 4.0.0.
    */
    const { $schema, module: _module, ...rest } = config
    // Resolved like every other scaffolded value: the root's placeholders are the same kind of
    // thing, and leaving them would write the placeholder's own text where an expression belongs.
    const resolved = this.resolveScaffoldedPlaceholders(rest)

    return `export default ${serializeConfiguration(resolved)}\n`
  }

  async _getConfigFileContents () {
    const config = {
      $schema: `https://schemas.platformatic.dev/wattpm/${this.platformaticVersion}.json`,
      watch: true,
      autoload: {
        path: this.config.autoload || this.applicationsFolder,
        exclude: ['docs']
      },
      ...getRuntimeWrappableProperties()
    }

    return config
  }

  async _afterPrepare () {
    const applicationsEnv = await this.prepareApplicationFiles()
    this.addEnvVars({
      ...this.config.env,
      ...applicationsEnv
    })

    this.updateRuntimeEnv(envObjectToString(this.config.env))

    this.addFile({
      path: '',
      file: '.env.sample',
      contents: envObjectToString(this.config.defaultEnv)
    })

    return {
      targetDirectory: this.targetDirectory,
      env: applicationsEnv
    }
  }

  async writeFiles () {
    for (const { application } of this.applications) {
      await application._beforeWriteFiles?.(this)
    }

    await super.writeFiles()

    if (!this.config.isUpdating) {
      for (const { application } of this.applications) {
        await application.writeFiles()
      }
    }

    for (const { application } of this.applications) {
      await application._afterWriteFiles?.(this)
    }
  }

  async prepareQuestions () {
    await this.populateFromExistingConfig()
  }

  setApplicationsDirectory () {
    this.applications.forEach(({ application }) => {
      if (!application.config) {
        // set default config
        application.setConfig()
      }
      let basePath
      if (this.existingConfig) {
        /*
          Resolved against the project, because the configuration says it relative to itself. The v3
          loader handed back an absolute path; reading the file directly hands back what it says.
        */
        basePath = resolve(this.targetDirectory, this.existingConfig.autoload.path)
      } else {
        basePath = join(this.targetDirectory, this.config.autoload || this.applicationsFolder)
      }
      this.applicationsBasePath = basePath
      application.setTargetDirectory(join(basePath, application.config.applicationName))
    })
  }

  setApplicationsConfig (configToOverride) {
    this.applications.forEach(application => {
      const originalConfig = application.config
      application.setConfig({
        ...originalConfig,
        ...configToOverride
      })
    })
  }

  async prepareApplicationFiles () {
    let applicationsEnv = {}
    for (const svc of this.applications) {
      const svcEnv = await svc.application.prepare()
      applicationsEnv = {
        ...applicationsEnv,
        ...svcEnv.env
      }
    }
    return applicationsEnv
  }

  getConfigFieldsDefinitions () {
    return []
  }

  setConfigFields () {
    // do nothing, makes no sense
  }

  async postInstallActions () {
    for (const { application } of this.applications) {
      await application.postInstallActions()
    }
  }

  async _getGeneratorForTemplate (dir, pkg) {
    const _require = createRequire(dir)
    const fileToImport = _require.resolve(pkg)
    return (await import(pathToFileURL(fileToImport))).Generator
  }

  /*
    Which applications a root already describes: the entries it lists, and the directories its
    autoload would discover. Neither needs an application's own configuration, which is the point.
  */
  async #listExistingApplications (config) {
    const ids = (config.applications ?? config.services ?? config.web ?? []).map(entry => entry.id).filter(Boolean)

    if (!config.autoload?.path) {
      return ids
    }

    const exclude = config.autoload.exclude ?? []
    const directory = join(this.targetDirectory, config.autoload.path)

    for (const entry of await readdir(directory, { withFileTypes: true }).catch(() => [])) {
      if (entry.isDirectory() && !exclude.includes(entry.name) && !ids.includes(entry.name)) {
        ids.push(entry.name)
      }
    }

    return ids
  }

  async loadFromDir () {
    const output = {
      applications: []
    }
    const runtimePkgConfigFileData = await this.readConfigurationFile(
      join(this.targetDirectory, await findAnyConfigurationFile(this.targetDirectory)),
      'root',
      this.targetDirectory
    )
    const applicationsPath = join(this.targetDirectory, runtimePkgConfigFileData.autoload.path)

    // load all applications
    const allApplications = await readdir(applicationsPath)
    for (const s of allApplications) {
      // check is a directory
      const currentApplicationPath = join(applicationsPath, s)
      const dirStat = await stat(currentApplicationPath)
      if (dirStat.isDirectory()) {
        // load the application config
        const configFile = await findAnyConfigurationFile(currentApplicationPath)
        // The environment is the runtime's: an application's expressions read the project's .env,
        // which lives at the root beside the configuration that autoloads it.
        const applicationPltJson = await this.readConfigurationFile(
          join(currentApplicationPath, configFile),
          'application',
          this.targetDirectory
        )
        // get module to load
        const template = applicationPltJson.module || getApplicationTemplateFromSchemaUrl(applicationPltJson.$schema)
        const Generator = await this._getGeneratorForTemplate(currentApplicationPath, template)
        const instance = new Generator({
          logger: this.logger
        })
        this.addApplication(instance, s)
        output.applications.push(await instance.loadFromDir(s, this.targetDirectory))
      }
    }
    return output
  }

  async update (newConfig) {
    let allApplicationsDependencies = {}
    const runtimeAddedEnvKeys = []

    this.config.isUpdating = true
    const currrentPackageJson = JSON.parse(await readFile(join(this.targetDirectory, 'package.json'), 'utf-8'))
    const currentRuntimeDependencies = currrentPackageJson.dependencies
    // check all applications are present with the same template
    const allCurrentApplicationsNames = this.applications.map(s => s.name)
    const allNewApplicationsNames = newConfig.applications.map(s => s.name)
    // load env file tool
    const envTool = createEnvFileTool({
      path: join(this.targetDirectory, '.env')
    })

    await envTool.load()

    const removedApplications = getArrayDifference(allCurrentApplicationsNames, allNewApplicationsNames)
    if (removedApplications.length > 0) {
      for (const removedApplication of removedApplications) {
        // handle application delete

        // delete env variables
        const s = this.applications.find(f => f.name === removedApplication)
        const allKeys = envTool.getKeys()
        allKeys.forEach(k => {
          if (k.startsWith(`PLT_${s.application.config.envPrefix}`)) {
            envTool.deleteKey(k)
          }
        })

        // delete dependencies
        const applicationPath = join(this.targetDirectory, this.applicationsFolder, s.name)
        const configFile = await findAnyConfigurationFile(applicationPath)
        const applicationPackageJson = await this.readConfigurationFile(
          join(applicationPath, configFile),
          'application',
          this.targetDirectory
        )
        if (applicationPackageJson.plugins && applicationPackageJson.plugins.packages) {
          applicationPackageJson.plugins.packages.forEach(p => {
            delete currrentPackageJson.dependencies[p.name]
          })
        }
        // delete directory
        await safeRemove(join(this.targetDirectory, this.applicationsFolder, s.name))
      }
      // throw new CannotRemoveApplicationOnUpdateError(removedApplications.join(', '))
    }

    // handle new applications
    for (const newApplication of newConfig.applications) {
      // create generator for the application
      const ApplicationGenerator = await this._getGeneratorForTemplate(
        join(this.targetDirectory, 'package.json'),
        newApplication.template
      )
      const applicationInstance = new ApplicationGenerator({
        logger: this.logger
      })
      const baseConfig = {
        isRuntimeContext: true,
        targetDirectory: join(this.targetDirectory, this.applicationsFolder, newApplication.name),
        applicationName: newApplication.name,
        plugin: true
      }
      if (allCurrentApplicationsNames.includes(newApplication.name)) {
        // update existing applications env values
        // otherwise, is a new application
        baseConfig.isUpdating = true

        // handle application's plugin differences
        const oldApplicationMetadata = await applicationInstance.loadFromDir(newApplication.name, this.targetDirectory)
        const oldApplicationPackages = oldApplicationMetadata.plugins.map(meta => meta.name)
        const newApplicationPackages = newApplication.plugins.map(meta => meta.name)
        const pluginsToRemove = getArrayDifference(oldApplicationPackages, newApplicationPackages)
        pluginsToRemove.forEach(p => delete currentRuntimeDependencies[p])
      } else {
        // add application to the generator
        this.applications.push({
          name: newApplication.name,
          application: applicationInstance
        })
      }
      applicationInstance.setConfig(baseConfig)
      this.setApplicationPort(applicationInstance, allNewApplicationsNames.indexOf(newApplication.name))
      applicationInstance.setConfigFields(newApplication.fields)

      const applicationEnvPrefix = `PLT_${applicationInstance.config.envPrefix}`
      for (const plug of newApplication.plugins) {
        await applicationInstance.addPackage(plug)
        for (const opt of plug.options) {
          const key = `${applicationEnvPrefix}_${opt.name}`
          runtimeAddedEnvKeys.push(key)
          const value = opt.value
          if (envTool.hasKey(key)) {
            envTool.updateKey(key, value)
          } else {
            envTool.addKey(key, value)
          }
        }
      }
      allApplicationsDependencies = { ...allApplicationsDependencies, ...applicationInstance.config.dependencies }
      const afterPrepareMetadata = await applicationInstance.prepare()
      await applicationInstance.writeFiles()
      // cleanup runtime env removing keys not present anymore in application plugins
      const allKeys = envTool.getKeys()
      allKeys.forEach(k => {
        if (k.startsWith(`${applicationEnvPrefix}_FST_PLUGIN`) && !runtimeAddedEnvKeys.includes(k)) {
          envTool.deleteKey(k)
        }
      })

      // add application env variables to runtime env
      Object.entries(afterPrepareMetadata.env).forEach(([key, value]) => {
        envTool.addKey(key, value)
      })
    }
    // update runtime package.json dependencies
    currrentPackageJson.dependencies = {
      ...currrentPackageJson.dependencies,
      ...allApplicationsDependencies
    }
    this.addFile({
      path: '',
      file: 'package.json',
      contents: JSON.stringify(currrentPackageJson, null, 2)
    })

    await this.writeFiles()
    // save new env
    await envTool.save()
  }

  async generateConfigFile () {
    this.updateRuntimeConfig(await super.generateConfigFile())
  }

  async generateEnv () {
    const serialized = await super.generateEnv()

    if (serialized) {
      this.updateRuntimeEnv(serialized)
    }
  }

  getRuntimeConfigFileObject () {
    return this.files.find(file => file.tags?.includes('runtime-config')) ?? null
  }

  getRuntimeEnvFileObject () {
    return this.files.find(file => file.tags?.includes('runtime-env')) ?? null
  }

  updateRuntimeConfig (config) {
    this.generatedConfig = config

    // Editing what is there, rather than replacing it with a rendering of what it evaluated to.
    if (this.existingConfigSource && !this.existingConfigFile.endsWith('.json')) {
      this.addFile({
        path: '',
        file: this.existingConfigFile,
        contents: this.#editExistingRoot(config),
        tags: ['runtime-config']
      })

      return
    }

    this.addFile({
      path: '',
      file: this.existingConfigFile ?? this.configurationFileName(),
      contents: this.serializeConfigFile(config),
      tags: ['runtime-config']
    })
  }

  /*
    An existing root is edited rather than rewritten, so that everything it says survives -- see
    `appendApplications`. A shape it cannot edit is reported here rather than papered over by
    writing the file from the loaded configuration, which would be a silent rewrite of every
    reference the root contains.
  */
  #editExistingRoot (config) {
    const edited = appendApplications(this.existingConfigSource, listedApplications(config), entry =>
      this.resolveScaffoldedPlaceholders(entry, rawSource)
    )

    if (edited === null) {
      throw new Error(
        `Cannot add applications to ${this.existingConfigFile}: its default export is not a configuration object this tool can edit. Add them by hand.`
      )
    }

    return edited
  }

  updateRuntimeEnv (contents) {
    this.addFile({
      path: '',
      file: '.env',
      contents,
      tags: ['runtime-env']
    })
  }
}

export class WrappedGenerator extends BaseGenerator {
  async prepare () {
    await this.getPlatformaticVersion()
    await this.#updateEnvironment()
    await this.#updatePackageJson()
    await this.#createConfigFile()
  }

  async #updateEnvironment () {
    this.addEnvVars(getRuntimeBaseEnvVars(this.config), { overwrite: false, default: true })

    this.addFile({
      path: '',
      file: '.env',
      contents: (await this.#readExistingFile('.env', '', '\n')) + envObjectToString(this.config.env)
    })

    this.addFile({
      path: '',
      file: '.env.sample',
      contents: (await this.#readExistingFile('.env.sample', '', '\n')) + envObjectToString(this.config.defaultEnv)
    })
  }

  async #updatePackageJson () {
    // Manipulate the package.json, if any
    const packageJson = JSON.parse(await this.#readExistingFile('package.json', '{}'))
    let { name, dependencies, devDependencies, scripts, engines: packageJsonEngines, ...rest } = packageJson

    // Add the dependencies
    dependencies = {
      ...dependencies,
      [this.module]: `^${this.platformaticVersion}`,
      platformatic: `^${this.platformaticVersion}`,
      wattpm: `^${this.platformaticVersion}`
    }

    // For easier readbility, sort dependencies and devDependencies by name
    dependencies = Object.fromEntries(Object.entries(dependencies).sort(([a], [b]) => a.localeCompare(b)))
    devDependencies = Object.fromEntries(Object.entries(devDependencies ?? {}).sort(([a], [b]) => a.localeCompare(b)))

    scripts ??= {}
    scripts.dev ??= this.config.devCommand
    scripts.build ??= this.config.buildCommand
    scripts.start ??= this.config.startCommand ?? 'wattpm start'

    this.addFile({
      path: '',
      file: 'package.json',
      contents: JSON.stringify(
        {
          name: name ?? this.projectName ?? this.runtimeName ?? basename(this.targetDirectory),
          scripts,
          dependencies,
          devDependencies,
          ...rest,
          engines: { ...packageJsonEngines, ...engines }
        },
        null,
        2
      )
    })
  }

  async #createConfigFile () {
    /*
      The wrapped single-app root. v3 spelled the runtime settings under a `runtime` key inside the
      application's own configuration; v4 has no such block, so they are the root's own and the
      application is the singular shorthand.
    */
    /*
      The application is the root's own, named by the singular shorthand. Without it the root
      describes a runtime with nothing in it -- it would load, and start none of the code it was
      wrapped around.

      Its capability is spelled as a plain object rather than a factory call because this file is
      read before anything is installed, and an import cannot be resolved in that state.
    */
    const config = {
      ...this.resolveScaffoldedPlaceholders(getRuntimeWrappableProperties()),
      application: { config: { module: this.module } }
    }

    this.addFile({
      path: '',
      file: this.configurationFileName(),
      contents: `export default ${serializeConfiguration(config)}\n`
    })
  }

  async #readExistingFile (path, emptyContents = '', suffix = '') {
    const filePath = join(this.targetDirectory, path)

    if (!existsSync(filePath)) {
      return emptyContents
    }

    const contents = await readFile(filePath, 'utf-8')
    return contents + suffix
  }
}
