'use strict'

const FileWatcher = require('./lib/file-watcher')
const findNearestString = require('./lib/find-nearest-string')
const deepmerge = require('./lib/deepmerge')
const isKeyEnabled = require('./lib/is-key-enabled')
const createServerConfig = require('./lib/create-server-config')
const isFileAccessible = require('./lib/is-file-accessible')
const packages = require('./lib/packages')
const { executeWithTimeout } = require('./lib/execute')
const errors = require('./lib/errors')
const getPkgManager = require('./lib/get-pkg-manager')
const match = require('./lib/match')
const schemaComponents = require('./lib/schema')
const { createDirectory, safeRemove } = require('./lib/directory')
const { withResolvers } = require('./lib/promises')
const { DestinationWritable } = require('./lib/streams/destination-writable')
const { MessagePortWritable } = require('./lib/streams/message-port-writable')
const { PinoWritable, createPinoWritable } = require('./lib/streams/pino-writable')
const { checkNodeVersionForServices } = require('./lib/check-node-version')

module.exports.FileWatcher = FileWatcher
module.exports.findNearestString = findNearestString
module.exports.deepmerge = deepmerge
module.exports.isKeyEnabled = isKeyEnabled
module.exports.isFileAccessible = isFileAccessible
module.exports.createServerConfig = createServerConfig
module.exports.hasDependency = packages.hasDependency
module.exports.getDependencyVersion = packages.getDependencyVersion
module.exports.getPlatformaticVersion = packages.getPlatformaticVersion
module.exports.checkForDependencies = packages.checkForDependencies
module.exports.getLatestNpmVersion = packages.getLatestNpmVersion
module.exports.getPkgManager = getPkgManager
module.exports.executeWithTimeout = executeWithTimeout
module.exports.errors = errors
module.exports.ensureLoggableError = errors.ensureLoggableError
module.exports.match = match
module.exports.schemaComponents = schemaComponents
module.exports.createDirectory = createDirectory
module.exports.safeRemove = safeRemove
module.exports.withResolvers = withResolvers
module.exports.DestinationWritable = DestinationWritable
module.exports.MessagePortWritable = MessagePortWritable
module.exports.PinoWritable = PinoWritable
module.exports.createPinoWritable = createPinoWritable
module.exports.checkNodeVersionForServices = checkNodeVersionForServices
