import { ok, strictEqual } from 'node:assert'
import { randomBytes } from 'node:crypto'
import { resolve } from 'node:path'
import { test } from 'node:test'
import { request } from 'undici'
import {
  buildRuntime,
  prepareRuntime,
  setFixturesDir,
  setHMRTriggerFile,
  startRuntime,
  verifyHMR
} from '../../../basic/test/helper.js'

setFixturesDir(resolve(import.meta.dirname, '../fixtures'))

// Turbopack's dev server (Next.js 16.2+) serves HMR over a per-client
// endpoint (/_next/hmr?id=<id>) instead of the legacy static
// /_next/webpack-hmr path. The id is normally generated by the browser's
// HMR bootstrap script; any unique string works for our purposes here.
const hmrClientId = randomBytes(16).toString('hex')

function websocketHMRHandler (message, resolveConnection, resolveReload) {
  // Connection readiness is now signaled by the WebSocket "open" event
  // (see verifyHMR in packages/basic/test/helper.js) rather than by an
  // explicit "sync" message, which Turbopack no longer sends.
  switch (message.type ?? message.action) {
    case 'serverComponentChanges':
      resolveReload()
  }
}

async function get (url, path) {
  const response = await request(url + path)
  const body = await response.body.text()

  strictEqual(response.statusCode, 200, `${path} returned ${response.statusCode}: ${body}`)
  return { body, headers: response.headers }
}

async function verifyZone (url, { path, name, assetPrefix, publicAsset, publicContents }) {
  const { body: html, headers } = await get(url, path)
  ok(headers['content-type']?.startsWith('text/html'))
  ok(html.includes(name))

  const script = html.match(/<script[^>]+src="([^"]*\/_next\/static\/[^"]+\.js[^"]*)"/)
  ok(script, `No JavaScript asset found in ${path}`)
  ok(script[1].startsWith(`${assetPrefix}/_next/static/`))

  const { headers: scriptHeaders } = await get(url, script[1].replaceAll('&amp;', '&'))
  ok(scriptHeaders['content-type']?.includes('javascript'))

  const stylesheet = html.match(/<link[^>]+href="([^"]*\/_next\/static\/[^"]+\.css[^"]*)"/)
  ok(stylesheet, `No stylesheet found in ${path}`)
  ok(stylesheet[1].startsWith(`${assetPrefix}/_next/static/`))

  const { headers: stylesheetHeaders } = await get(url, stylesheet[1].replaceAll('&amp;', '&'))
  ok(stylesheetHeaders['content-type']?.startsWith('text/css'))

  const { body: asset } = await get(url, publicAsset)
  strictEqual(asset.trim(), publicContents)
}

async function verifyZones (url) {
  await verifyZone(url, {
    path: '/',
    name: 'Frontend zone',
    assetPrefix: '',
    publicAsset: '/frontend.txt',
    publicContents: 'frontend asset'
  })
  await verifyZone(url, {
    path: '/blog',
    name: 'Blog zone',
    assetPrefix: '/blog',
    publicAsset: '/blog/blog.txt',
    publicContents: 'blog asset'
  })
}

test('serves multiple Next.js zones in development', async t => {
  const { root, runtime } = await prepareRuntime(t, 'multi-zones', false)
  const url = await startRuntime(t, runtime)

  await verifyZones(url)

  setHMRTriggerFile('services/blog/src/app/page.js')
  await verifyHMR(root, runtime, url, `/blog/_next/hmr?id=${hmrClientId}`, undefined, websocketHMRHandler)
})

test('builds and serves multiple Next.js zones in production', async t => {
  const { root, runtime } = await prepareRuntime(t, 'multi-zones', true)

  await buildRuntime(root)

  const url = await startRuntime(t, runtime)
  await verifyZones(url)
})
